// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqyhBu8W3Umr6e7Q3gpfICrP2xN9PNUR4',
    appId: '1:183000530280:web:4e3e68f2a77e97e7b96add',
    messagingSenderId: '183000530280',
    projectId: 'vanapp-86ca7',
    authDomain: 'vanapp-86ca7.firebaseapp.com',
    storageBucket: 'vanapp-86ca7.firebasestorage.app',
    measurementId: 'G-MYYRTS76FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByOq8KJzcFT_avL6oWK30oVIvKwWTZqDs',
    appId: '1:183000530280:android:5da64d7c11f8c1aab96add',
    messagingSenderId: '183000530280',
    projectId: 'vanapp-86ca7',
    storageBucket: 'vanapp-86ca7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU8b0sVz7z7doakxPjSjMbV4Vz3xBfscY',
    appId: '1:183000530280:ios:357ffc9843473f17b96add',
    messagingSenderId: '183000530280',
    projectId: 'vanapp-86ca7',
    storageBucket: 'vanapp-86ca7.firebasestorage.app',
    iosBundleId: 'com.example.vanappfront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU8b0sVz7z7doakxPjSjMbV4Vz3xBfscY',
    appId: '1:183000530280:ios:357ffc9843473f17b96add',
    messagingSenderId: '183000530280',
    projectId: 'vanapp-86ca7',
    storageBucket: 'vanapp-86ca7.firebasestorage.app',
    iosBundleId: 'com.example.vanappfront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqyhBu8W3Umr6e7Q3gpfICrP2xN9PNUR4',
    appId: '1:183000530280:web:369b5bf41a745e05b96add',
    messagingSenderId: '183000530280',
    projectId: 'vanapp-86ca7',
    authDomain: 'vanapp-86ca7.firebaseapp.com',
    storageBucket: 'vanapp-86ca7.firebasestorage.app',
    measurementId: 'G-5FEBP7N7M9',
  );
}
